name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: "24"
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
          restore-keys: "${{ runner.os }}-m2"

      - name: Maven install
        run: mvn --batch-mode --update-snapshots clean install

      - name: Run tests with Maven
        run: mvn --batch-mode test

      - name: Run Checkstyle with Maven
        run: mvn --batch-mode checkstyle:check

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-results
          path: "./**/target/checkstyle-result.xml"
